name: CI POI

on:
  push:
    branches: [ master ]
    paths: 
    - apis/poi/**
  pull_request:
    branches: [ master ]
    paths: 
    - apis/poi/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.801     

    - name: Show Version
      run: dotnet --version

    - name: Install dependencies
      run: dotnet restore
      working-directory: apis/poi
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: apis/poi
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: apis/poi
      
    - name: Build Docker image
              
      env:
        SQL_USER: ${{ secrets.SQL_USER }}
        SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        SQL_SERVER: openhackejs89fy7sql.database.windows.net
        SQL_DBNAME: mydrivingDB
       
      working-directory: apis/poi/web
      
      run: |
        docker login docker.pkg.github.com -u kostinams -p ${{ secrets.GITHUB_TOKEN }}
        docker build .
        docker tag test docker.pkg.github.com/openhack2020/tripsinsights/poi:1
        docker push docker.pkg.github.com/openhack2020/tripsinsights/poi:1
      
    - name: error 
      if: ${{ failure() }}
      uses: JasonEtco/create-an-issue@v2
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
