name: CI User-Java 

on:
  push:
    branches: [ master ]
    paths: 
    - apis/user-java/**
    - .github/workflows/user-java** # trigger workflow when this file is changed
#  pull_request:
#    branches: [ master ]
#    paths:
#    - apis/user-java/**
#    - .github/workflows/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v1  
      
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: openhack2020/tripsinsights/userjava
        path: apis/user-java
        # tag_with_sha: false
        tags: ${{env.GITHUB_SHA}} 
      env:
       SQL_USER: ${{ secrets.SQL_USER }}
       SQL_SERVER: openhackejs89fy7sql.database.windows.net
       SQL_DBNAME: mydrivingDB  
       SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
    
    - name: create issue on error
      uses: JasonEtco/create-an-issue@v2   
      if: ${{ failure() }}
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
