name: CI User-Java 

on:
  push:
    branches: [ master ]
    paths: 
    - apis/user-java/**
    - .github/workflows/**
  pull_request:
    branches: [ master ]
    paths:
    - apis/user-java/**
    - .github/workflows/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for 'userjava'
      run: docker build . --file Dockerfile --tag userjava:$(date +%s)
      working-directory: apis/user-java
